package com.archimatetool.recommender.contribution;

public class TestJSONData {
	
	public static String STANDARD_RESPONSE = "[\r\n"
			+ "	{\r\n"
			+ "        \"component\": {\r\n"
			+ "            \"id\": \"1544\",\r\n"
			+ "            \"modelId\": \"11f5304f\",\r\n"
			+ "            \"name\": \"mail\",\r\n"
			+ "            \"type\": \"BusinessInterface\"\r\n"
			+ "        },\r\n"
			+ "        \"score\": 1.0000000000000002\r\n"
			+ "    }, {\r\n"
			+ "        \"component\": {\r\n"
			+ "            \"id\": \"1540\",\r\n"
			+ "            \"modelId\": \"11f5304f\",\r\n"
			+ "            \"name\": \"phone\",\r\n"
			+ "            \"type\": \"BusinessInterface\"\r\n"
			+ "        },\r\n"
			+ "        \"score\": 1.0000000000000002\r\n"
			+ "    }, {\r\n"
			+ "        \"component\": {\r\n"
			+ "            \"id\": \"id-4fa92c24\",\r\n"
			+ "            \"modelId\": \"id-03f9559e\",\r\n"
			+ "            \"name\": \"Working group 1\",\r\n"
			+ "            \"type\": \"BusinessActor\"\r\n"
			+ "        },\r\n"
			+ "        \"score\": 1.0000000000000002\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "]\r\n"
			+ "";

	
	public static String INVALID_RESPONSE = "[\r\n"
			+ "	{\r\n"
			+ "        \"component\": {            \r\n"
			+ "            \"modelId\": \"11f5304f\",            \r\n"
			+ "            \"type\": \"BusinessInterface\"\r\n"
			+ "        },\r\n"
			+ "        \"score\": 1.0000000000000002\r\n"
			+ "    }, {\r\n"
			+ "        \"component\": {\r\n"
			+ "            \"id\": \"1540\",\r\n"
			+ "            \"modelId\": \"11f5304f\",\r\n"
			+ "            \"name\": \"phone\",\r\n"
			+ "            \"type\": \"BusinessInterface\"\r\n"
			+ "        }\r\n"
			+ "        \r\n"
			+ "    }, {\r\n"
			+ "        \"component\": {\r\n"
			+ "            \"id\": \"id-4fa92c24\",\r\n"
			+ "            \"modelId\": \"id-03f9559e\",\r\n"
			+ "            \"name\": \"Working group 1\",\r\n"
			+ "            \"type\": \"BusinessActor\"\r\n"
			+ "        },\r\n"
			+ "        \"score\": 1.0000000000000002\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "]\r\n"
			+ "";
}
